name: flutter_application_1
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0" # Sesuaikan dengan versi Flutter yang Anda gunakan

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  carousel_slider: ^5.0.0
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  google_nav_bar: ^5.0.6
  google_fonts: ^6.2.1
  animated_theme_switcher: ^2.0.10
  line_awesome_flutter: ^3.0.1
  flutter_screenutil: ^5.9.3
  ionicons: ^0.2.2
  mqtt_client: ^10.5.1
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - Images/ # Pastikan folder ini ada di root proyek Anda
